### ISSUE TITLE
1.20.1 Support

### ISSUE THREAD

**Issue by Mr-ConQueso** [AceTheEldritchKing/Cataclysm_Spellbooks#5]
I'm aware this mod is in its very early stages of development, but I want to argue that continuing development in 1.20 will be much more productive for giving this incredible project the attention it needs, as most current modpacks are running on that version.

I will attempt to update it myself, however my java knowledge is limited, I'll keep this thread updated if I get any further.

**Comment by Danmccool** [comment]
the mod will never be ported to 1.20.1

**Comment by AceTheEldritchKing** [comment]
> the mod will never be ported to 1.20.1

Incorrect, it will be officially ported once the mod is almost fully feature complete.

**Comment by AceTheEldritchKing** [comment]
> I'm aware this mod is in its very early stages of development, but I want to argue that continuing development in 1.20 will be much more productive for giving this incredible project the attention it needs, as most current modpacks are running on that version.
> 
> I will attempt to update it myself, however my java knowledge is limited, I'll keep this thread updated if I get any further.

If want to make a 1.20.1 port, go ahead! The reason I'm not doing 1.20.1 at the same time is that it feels too resource intensive for me at the moment. I would rather have a complete product to port rather than something incomplete that I will have to update everytime I fix a bug or do a major update for.

**Comment by Danmccool** [comment]
> > the mod will never be ported to 1.20.1
> 
> Incorrect, it will be officially ported once the mod is almost fully feature complete.

You Are Lying it Will Take 3847582391473143 days To Port To 1.20.1
